version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nest
    command: "/bin/sh -c 'nginx; trap exit TERM; while :; do sleep 6h  & wait $${!}; nginx -s reload; done;'"

  nest:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    environment:
      - EMAIL_AUTH_EMAIL=${EMAIL_AUTH_EMAIL}
      - EMAIL_AUTH_PASSWORD=${EMAIL_AUTH_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_FROM_USER_NAME=${EMAIL_FROM_USER_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LAUNCH_ENV=docker-compose

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
