name: auto-deploy

on:
  push:
    branches: [feature/**]
    # types: [closed] # when PR closed
    # branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: build
        run: |
          yarn install
          yarn build

      # --------------
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

          # aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://liontown/$GITHUB_SHA.zip
      - name: Upload to S3
        run: |
          aws s3 rm --region ap-northeast-2 s3://liontown/ --recursive
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://liontown/liontown/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name liontown
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name liontown_group
          --s3-location bucket=liontown,bundleType=zip,key=liontown/$GITHUB_SHA.zip

      # --------------
      # - name: S3 bucket
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws s3 rm --region ap-northeast-2 s3://liontown/ --recursive
      #     aws s3 cp --recursive --region ap-northeast-2 dist s3://liontown
      # - name: CodeDeploy
      #   run: aws deploy create-deployment
      #     --application-name liontown
      #     --deployment-config-name CodeDeployDefault.OneAtATime
      #     --deployment-group-name liontown_group
      #     --s3-location bucket=liontown,bundleType=zip,key=dist/build.zip
