name: auto-deploy

on:
  push:
    branches: [feature/**]
    # types: [closed] # when PR closed
    # branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged

    # Steps : 작업의 일부로 실행될 일련의 작업을 나타냅니다.
    steps:
      # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE 아래에 있는 저장소를 체크아웃합니다.
      - uses: actions/checkout@v2
      # Runs ssh deploy for CI, CD
      - name: auto deploy to github actions
        # if: github.event_name == 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }} # default : 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }} && git pull
            yarn install
            yarn build
            yarn start
