name: slack

on:
  push:
    branches: [develop, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Type Check'

    steps:
      # ts 타입 체크
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Type Check
        run: |
          yarn install
          yarn tsc -v
          yarn tsc

      # 슬랙에 알림
      - name: action-slack
        uses: 8398a7/action-slack@v3

        with:
          status: custom
          fields: workflow,job,commit,repo,author,pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields:
                 title: '라이언킹 타입체크',
                 title_link: '${{ github.event.push.html_url }}',
                 thumb_url: '${{ github.event.push.user.avatar_url }}',
               }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # 실패 성공 여부와 상관없이 알림
    permissions:
      contents: read
      actions: read
